### ISSUE TITLE
Don't know what you code in but please format your code.

### ISSUE THREAD

**Issue by surajmandalcell** [josiahsrc/dough#1]
^

**Comment by josiahsrc** [comment]
Hi @surajmandalcell ,

I'm using the vscode plugin `dart-code.dart-code` which provides auto-formatting and I auto-format frequently. Could you expand on the issue you're seeing with the formatting?

Thanks

**Comment by surajmandalcell** [comment]
Hi, use the default ```flutter format```

https://pub.dev/packages/dough#-analysis-tab-

It is effecting your package.

**Comment by josiahsrc** [comment]
I had no idea! Thanks for catching this. I just ran `dart format` and republished the package. The health is now at 100

**Comment by surajmandalcell** [comment]
Nice!!
Happy to help 😃
