### ISSUE TITLE
Sensors introduces platform dependency

### ISSUE THREAD

**Issue by josiahsrc** [josiahsrc/dough#15]
Sensors introduces platform dependency for android and iOS and does not include the mac/linux/windows platform. This is causing the package to lose pub points.

Find a way to support accelerometer functionality on mobile platforms (for GyroDough) while maintaining support for web/desktop platforms.

https://pub.dev/packages/dough/score

**Comment by josiahsrc** [comment]
An alternative to this would be to have two packages
1. Platform independent library, `Dough`, which has all widgets and has not platform dependencies
2. Platform dependent library, `Mobile Dough`, which uses sensors

**Comment by cyberpwnn** [comment]
Or if your lazy and dont even need gyrodough https://pub.dev/packages/senseless_dough

**Comment by josiahsrc** [comment]
New sensors package here: https://pub.dev/packages/dough_sensors
