### ISSUE TITLE
Migrate to null safety

### ISSUE THREAD

**Issue by josiahsrc** [josiahsrc/dough#17]
Dart team recommends that packages migrate to null-safety. Create/test a null safety API for dough.

**Comment by britannio** [comment]
null safety is still in technical preview right?

**Comment by josiahsrc** [comment]
@britannio Yes, but flutter recommends that package maintainers should start switching over to null safety

**Comment by britannio** [comment]
@josiahsrc Null safety is now stable, are you planning on migrating?

**Comment by josiahsrc** [comment]
@britannio Currently working on this when I get time. Branch is here: https://github.com/josiahsrc/flutter_dough/tree/v1.0.0-nullsafety

**Comment by josiahsrc** [comment]
@britannio I just finished up the migration. Let me know if you experience any issues with the migration. Thanks!
